// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "Améliorateur de prompt",
    "tooltip": "Améliorer le prompt",
    "tooltipFull": "Réécrire le prompt pour fournir plus de contexte et améliorer les réponses de l'agent",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "Amélioration du prompt...",
    "readyToEnhance": "Définissez le fournisseur, le modèle et le délai d'expiration, puis lancez l'amélioration.",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "Paramètres d'amélioration",
    "provider": "Fournisseur",
    "model": "Modèle",
    "noModel": "Aucun modèle",
    "timeoutSeconds": "Délai d'expiration (secondes)",
    "runEnhancement": "Lancer l'amélioration",
    "originalPrompt": "Prompt original",
    "enhancedPrompt": "Prompt amélioré",
    "useEnhanced": "Utiliser l'amélioré",
    "keepOriginal": "Conserver l'original",
    "enhanceFailed": "Échec de l'amélioration du prompt",
    "failedTimeout": "L'amélioration du prompt a expiré après {{seconds}} s. Veuillez réessayer",
    "failedWorkspace": "L'espace de travail n'est pas prêt pour l'amélioration du prompt",
    "failedEmpty": "Le moteur a renvoyé une amélioration vide. Veuillez réessayer",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "Échec de l'amélioration du prompt",
    "emptyPrompt": "Veuillez d'abord saisir un prompt",
    "copyEnhanced": "Copier l'amélioré"
  }
};

export default promptEnhancer;
