// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "提示詞增強器",
    "tooltip": "增強提示詞",
    "tooltipFull": "改寫提示詞以提供更多脈絡並改善 Agent 回應",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "正在增強提示詞…",
    "readyToEnhance": "設定提供者、模型與逾時後即可開始增強。",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "增強設定",
    "provider": "提供者",
    "model": "模型",
    "noModel": "無模型",
    "timeoutSeconds": "逾時（秒）",
    "runEnhancement": "開始增強",
    "originalPrompt": "原始提示詞",
    "enhancedPrompt": "增強後提示詞",
    "useEnhanced": "使用增強版",
    "keepOriginal": "保留原始版",
    "enhanceFailed": "增強提示詞失敗",
    "failedTimeout": "提示詞潤飾逾時（{{seconds}} 秒），請重試",
    "failedWorkspace": "目前工作區尚未就緒，無法潤飾提示詞",
    "failedEmpty": "引擎回傳了空的潤飾結果，請重試",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "提示詞潤飾失敗",
    "emptyPrompt": "請先輸入提示詞",
    "copyEnhanced": "複製增強版"
  }
};

export default promptEnhancer;
