// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/reasoning.ts; keys mirror the English source.
const reasoning = {
  "reasoning": {
    "title": "選擇推理深度",
    "default": "預設 (Default)",
    "claudeDefault": "預設 (Default)",
    "grokDefault": "預設 (Default)",
    "defaultDescription": "使用引擎預設的推理行為",
    "off": {
      "label": "關閉 (Off)",
      "description": "關閉思考，快速回應"
    },
    "minimal": {
      "label": "最低 (Minimal)",
      "description": "最低思考強度"
    },
    "low": {
      "label": "低 (Low)",
      "description": "以基本推理快速回應"
    },
    "medium": {
      "label": "中 (Medium)",
      "description": "均衡思考（預設）"
    },
    "high": {
      "label": "高 (High)",
      "description": "為複雜任務進行深度推理"
    },
    "xhigh": {
      "label": "超高 (Extra High)",
      "description": "超高推理深度"
    },
    "max": {
      "label": "最高 (Max)",
      "description": "最高推理深度"
    },
    "ultra": {
      "label": "超強 (Ultra)",
      "description": "最高推理強度，並自動委派任務"
    }
  }
};

export default reasoning;
