// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "Aprimorador de Prompt",
    "tooltip": "Aprimorar prompt",
    "tooltipFull": "Reescreve o prompt para fornecer mais contexto e melhorar as respostas do agente",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "Aprimorando prompt...",
    "readyToEnhance": "Defina o provedor, o modelo e o tempo limite e inicie o aprimoramento.",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "Configurações de aprimoramento",
    "provider": "Provedor",
    "model": "Modelo",
    "noModel": "Sem modelo",
    "timeoutSeconds": "Tempo limite (segundos)",
    "runEnhancement": "Iniciar aprimoramento",
    "originalPrompt": "Prompt original",
    "enhancedPrompt": "Prompt aprimorado",
    "useEnhanced": "Usar aprimorado",
    "keepOriginal": "Manter original",
    "enhanceFailed": "Falha ao aprimorar o prompt",
    "failedTimeout": "O aprimoramento do prompt expirou após {{seconds}}s. Tente novamente",
    "failedWorkspace": "O workspace não está pronto para o aprimoramento do prompt",
    "failedEmpty": "O motor retornou um aprimoramento vazio. Tente novamente",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "Falha ao aprimorar o prompt",
    "emptyPrompt": "Digite um prompt primeiro",
    "copyEnhanced": "Copiar aprimorado"
  }
};

export default promptEnhancer;
