// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "プロンプト強化",
    "tooltip": "プロンプトを強化",
    "tooltipFull": "プロンプトを書き換えて文脈を補い、Agent の応答を改善します",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "プロンプトを強化中...",
    "readyToEnhance": "プロバイダー、モデル、タイムアウトを設定してから強化を開始してください。",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "強化設定",
    "provider": "プロバイダー",
    "model": "モデル",
    "noModel": "モデルなし",
    "timeoutSeconds": "タイムアウト（秒）",
    "runEnhancement": "強化を開始",
    "originalPrompt": "元のプロンプト",
    "enhancedPrompt": "強化されたプロンプト",
    "useEnhanced": "強化版を使用",
    "keepOriginal": "元のまま保持",
    "enhanceFailed": "プロンプトの強化に失敗しました",
    "failedTimeout": "プロンプトの強化が {{seconds}} 秒でタイムアウトしました。再試行してください",
    "failedWorkspace": "ワークスペースの準備ができていないため、プロンプトを強化できません",
    "failedEmpty": "エンジンが空の強化結果を返しました。再試行してください",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "プロンプトの強化に失敗しました",
    "emptyPrompt": "先にプロンプトを入力してください",
    "copyEnhanced": "強化版をコピー"
  }
};

export default promptEnhancer;
