// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "Mejorador de prompts",
    "tooltip": "Mejorar prompt",
    "tooltipFull": "Reescribe el prompt para aportar más contexto y mejorar las respuestas del agente",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "Mejorando prompt...",
    "readyToEnhance": "Configura el proveedor, el modelo y el tiempo de espera, luego inicia la mejora.",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "Ajustes de mejora",
    "provider": "Proveedor",
    "model": "Modelo",
    "noModel": "Sin modelo",
    "timeoutSeconds": "Tiempo de espera (segundos)",
    "runEnhancement": "Iniciar mejora",
    "originalPrompt": "Prompt original",
    "enhancedPrompt": "Prompt mejorado",
    "useEnhanced": "Usar mejorado",
    "keepOriginal": "Mantener original",
    "enhanceFailed": "No se pudo mejorar el prompt",
    "failedTimeout": "La mejora del prompt agotó el tiempo tras {{seconds}} s. Inténtalo de nuevo",
    "failedWorkspace": "El espacio de trabajo no está listo para mejorar el prompt",
    "failedEmpty": "El motor devolvió una mejora vacía. Inténtalo de nuevo",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "Error al mejorar el prompt",
    "emptyPrompt": "Introduce primero un prompt",
    "copyEnhanced": "Copiar mejorado"
  }
};

export default promptEnhancer;
