// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "प्रॉम्प्ट एन्हांसर",
    "tooltip": "प्रॉम्प्ट एन्हांस करें",
    "tooltipFull": "अधिक संदर्भ देने और Agent प्रतिक्रियाओं को बेहतर बनाने के लिए प्रॉम्प्ट को फिर से लिखें",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "प्रॉम्प्ट एन्हांस किया जा रहा है...",
    "readyToEnhance": "प्रोवाइडर, मॉडल और टाइमआउट सेट करें, फिर एन्हांसमेंट शुरू करें।",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "एन्हांसमेंट सेटिंग्स",
    "provider": "प्रोवाइडर",
    "model": "मॉडल",
    "noModel": "कोई मॉडल नहीं",
    "timeoutSeconds": "टाइमआउट (सेकंड)",
    "runEnhancement": "एन्हांसमेंट शुरू करें",
    "originalPrompt": "मूल प्रॉम्प्ट",
    "enhancedPrompt": "एन्हांस किया गया प्रॉम्प्ट",
    "useEnhanced": "एन्हांस किया गया उपयोग करें",
    "keepOriginal": "मूल रखें",
    "enhanceFailed": "प्रॉम्प्ट एन्हांस करने में विफल",
    "failedTimeout": "प्रॉम्प्ट एन्हांसमेंट {{seconds}} सेकंड बाद समय-सीमा समाप्त। पुनः प्रयास करें",
    "failedWorkspace": "प्रॉम्प्ट एन्हांसमेंट के लिए वर्कस्पेस तैयार नहीं है",
    "failedEmpty": "इंजन ने खाली एन्हांसमेंट लौटाया। पुनः प्रयास करें",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "प्रॉम्प्ट एन्हांसमेंट विफल",
    "emptyPrompt": "कृपया पहले एक प्रॉम्प्ट दर्ज करें",
    "copyEnhanced": "एन्हांस किया गया कॉपी करें"
  }
};

export default promptEnhancer;
