// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "Улучшение промпта",
    "tooltip": "Улучшить промпт",
    "tooltipFull": "Переписать промпт, чтобы дать больше контекста и улучшить ответы Agent",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "Улучшение промпта…",
    "readyToEnhance": "Задайте провайдера, модель и таймаут, затем запустите улучшение.",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "Настройки улучшения",
    "provider": "Провайдер",
    "model": "Модель",
    "noModel": "Нет модели",
    "timeoutSeconds": "Таймаут (секунды)",
    "runEnhancement": "Запустить улучшение",
    "originalPrompt": "Исходный промпт",
    "enhancedPrompt": "Улучшенный промпт",
    "useEnhanced": "Использовать улучшенный",
    "keepOriginal": "Оставить исходный",
    "enhanceFailed": "Не удалось улучшить промпт",
    "failedTimeout": "Улучшение промпта превысило тайм-аут {{seconds}} с. Повторите попытку",
    "failedWorkspace": "Рабочая область не готова к улучшению промпта",
    "failedEmpty": "Движок вернул пустой результат улучшения. Повторите попытку",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "Не удалось улучшить промпт",
    "emptyPrompt": "Сначала введите промпт",
    "copyEnhanced": "Копировать улучшенный"
  }
};

export default promptEnhancer;
