// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
// AUTO-GENERATED by scripts/i18n/build-locale.ts — do not edit by hand.
// Machine translation of src/i18n/locales/en/promptEnhancer.ts; keys mirror the English source.
const promptEnhancer = {
  "promptEnhancer": {
    "title": "프롬프트 개선 도구",
    "tooltip": "프롬프트 개선",
    "tooltipFull": "더 많은 컨텍스트를 제공하고 Agent 응답을 개선하도록 프롬프트를 다시 작성합니다",
    "shortcut": "⌘/ / Ctrl+/",
    "enhancing": "프롬프트 개선 중...",
    "readyToEnhance": "제공자, 모델, 시간 초과를 설정한 다음 개선을 시작하세요.",
    "subtitle": "Side-by-side review",
    "advancedTimeout": "Advanced · Timeout",
    "intensityLabel": "Rewrite intensity",
    "intensityLightHint": "Polish wording; do not expand a short draft",
    "intensityStructHint": "Add sections only when they introduce new constraints",
    "intensityExecHint": "Add actions and verification without inventing facts",
    "noEnabledEngine": "No enabled CLI. Enable an engine in vendor settings first.",
    "originalEditable": "Editable",
    "diffLegend": "Green = added",
    "waitingEnhance": "Waiting to enhance",
    "enhancingWithEngine": "{{engine}} is enhancing",
    "intensity": {
      "light": "Light",
      "struct": "Structured",
      "exec": "Executable"
    },
    "runSettings": "개선 설정",
    "provider": "제공자",
    "model": "모델",
    "noModel": "모델 없음",
    "timeoutSeconds": "시간 초과 (초)",
    "runEnhancement": "개선 시작",
    "originalPrompt": "원본 프롬프트",
    "enhancedPrompt": "개선된 프롬프트",
    "useEnhanced": "개선본 사용",
    "keepOriginal": "원본 유지",
    "enhanceFailed": "프롬프트 개선에 실패했습니다",
    "failedTimeout": "프롬프트 개선이 {{seconds}}초 후 시간 초과되었습니다. 다시 시도하세요",
    "failedWorkspace": "워크스페이스가 준비되지 않아 프롬프트를 개선할 수 없습니다",
    "failedEmpty": "엔진이 빈 개선 결과를 반환했습니다. 다시 시도하세요",
    "failedDshCatalogId": "DSH needs a provider/model catalog id. Select a DSH catalog row instead of a bare runtime name like {{model}}.",
    "failedGeneric": "프롬프트 개선에 실패했습니다",
    "emptyPrompt": "먼저 프롬프트를 입력하세요",
    "copyEnhanced": "개선본 복사"
  }
};

export default promptEnhancer;
